/* eslint-disable prettier/prettier */
const Data = {
  Claims: [
    {
      ClaimNo: '0129857',
      SubmissionDate: '2020-12-24',
      Provider: {
        Name: null,
        Speciality: null,
        ProviderID: null,
        Phone: null,
        ProviderType: null,
      },
      MemberId: '1234675889',
      MemberFirstName: 'XXXX',
      MemberLastName: 'YYY',
      DiagnosisCode: [
        {
          Diagnosis: 'Z13.9 - Encounter for screening, unspecified',
        },
      ],
      BillDate: '2020-12-24',
      BillablePeriod: {
        Start: '05-11-2020',
        End: '05-11-2020',
      },
      Status: 'paid',
      TotalBilledAmount: '500',
      TotalAllowedAmount: '0',
      TotalPaidAmount: '0',
      TotalPatientAmount: '0',
      ServiceLines: [
        {
          ServiceID: '1',
          ServiceName: null,
          StartDate: '05-11-2020',
          EndDate: null,
          BilledAmount: '500',
          AllowedAmount: '0',
          PaidAmount: '0',
          PatientAmount: '0',
        },
      ],
    },
  ],
  Procedures: [
    {
      ClaimNo: 'AA12345XY478',
      ProCode: 'MADB002',
      Provider: {
        Name: 'Maria Gorbovitsky, MD',
        Speciality: 'Primary Care Doctor- Internist',
      },
      Name: 'Editmermeber Test',
    },
    {
      ClaimNo: 'AD67899GK879',
      ProCode: 'PQDM232',
      Provider: {
        Name: 'Asher Tulsky, MD',
        Speciality: 'Primary Care Doctor- Adult Primary Care',
      },
      Name: 'Editmermeber Test',
    },
  ],
  Immunizations: [
    {
      MemberId: '12356789123',
      id: 'Jo8hZskm0KEyY6o97IvIebmxrPiFJqbDJ5JKtcx1up',
      Date: '2018-10-25T01:02:00.000Z',
      vaccine: '150 - Fluzone Quadrivalent 0.5 ML Intramuscular Suspension',
      doseQuantity: '',
      doseNumber: '',
      Manufacturer: '',
      LotNumber: 'uj105af',
    },
    {
      MemberId: '12356789123',
      Date: '12/20/2020',
      vaccine: '115 - Tdap',
      doseQuantity: '2.5 µg',
      doseNumber: '2',
      Manufacturer: 'Protein Sciences Corporation',
      LotNumber: 'K34',
    },
    {
      MemberId: '12356789123',
      Date: '12/20/2020',
      vaccine: '115 - Tdap',
      doseQuantity: '2.5 µg',
      doseNumber: '2',
      Manufacturer: 'Protein Sciences Corporation',
      LotNumber: 'K34',
    },
    {
      MemberId: '12356789123',
      Date: '12/20/2020',
      vaccine: '115 - Tdap',
      doseQuantity: '2.5 µg',
      doseNumber: '2',
      Manufacturer: 'Protein Sciences Corporation',
      LotNumber: 'K34',
    },
  ],
  Prescriptions: [
    {
      Provider: {
        Name: 'Maria Gorbovitsky, MD',
        Speciality: 'Primary Care Doctor- Internist',
      },
      Date: '07/22/2020',
      DrugName: [
        {DrugName: 'Delasone (prednisone)', Dosage: 'Once-a-day'},
        {DrugName: 'Lipitor (atorvastatin)', Dosage: 'Every morning'},
        {DrugName: 'Amoxil (amoxicillin)', Dosage: 'Every other day'},
      ],
    },
    {
      Provider: {
        Name: 'Asher Tulsky, MD',
        Speciality: 'Adult Primary Care',
      },
      Date: '06/20/2020',
      DrugName: [
        {DrugName: 'Delasone (prednisone)', Dosage: 'Once-a-day'},
        {DrugName: 'Amoxil (amoxicillin)', Dosage: 'Every other day'},
        {DrugName: 'Lipitor (atorvastatin)', Dosage: 'Every morning'},
      ],
    },
  ],
  ProvidersSeen: [
    {
      Provider: {
        Name: 'Maria Gorbovitsky, MD',
        Speciality: 'Primary Care Doctor- Internist',
        Phone: '+019865475562244',
      },
      Date: '07/22/2020',
    },
    {
      Provider: {
        Name: 'Asher Tulsky, MD',
        Speciality: 'Primary Care Doctor- Adult Primary Care',
        Phone: '+01865954859966',
      },
      Date: '06/20/2020',
    },
  ],
  LabResults: [
    {
      MemberId: '12356789123',
      id: 'THrnUszcVIxcKWyfDg2mwiGpSZKLZM6Nv0cMKkx1up',
      TestCode: '10582-5',
      TestName: 'Cervical Mucus',
      Date: '12/31/2019',
      Result: '.2 mg/dL',
      RangeLowValue: '0.2',
      RangeLowUnit: 'mg/dL',
      RangeHighValue: '0.5',
      RangeHighUnit: 'mg/dL',
      RangeText: '.2',
      Interpretation: 'low',
    },
    {
      MemberId: '12356789123',
      id: 'THrnUszcVIxcKWyfDg2mwiGpSZKLZM6Nv0cMKkx1up',
      TestCode: '10582-5',
      TestName: 'Cervical Mucus',
      Date: '12/31/2019',
      Result: '.2 mg/dL',
      RangeLowValue: '0.2',
      RangeLowUnit: 'mg/dL',
      RangeHighValue: '0.5',
      RangeHighUnit: 'mg/dL',
      RangeText: '.2',
      Interpretation: 'low',
    },
    {
      MemberId: '12356789123',
      id: 'THrnUszcVIxcKWyfDg2mwiGpSZKLZM6Nv0cMKkx1up',
      TestCode: '10582-5',
      TestName: 'Cervical Mucus',
      Date: '12/31/2019',
      Result: '.2 mg/dL',
      RangeLowValue: '0.2',
      RangeLowUnit: 'mg/dL',
      RangeHighValue: '0.5',
      RangeHighUnit: 'mg/dL',
      RangeText: '.2',
      Interpretation: 'low',
    },
  ],
  VitalSigns: [
    {
      MemberId: '12356789123',
      TestCode: '10545-5',
      TestName: 'Body Temperature',
      Date: '12/31/2019',
      Result: '98 F',
      RangeLowValue: '80',
      RangeLowUnit: 'F',
      RangeHighValue: '110',
      RangeHighUnit: 'F',
      RangeText: '80',
      Interpretation: 'normal',
    },
    {
      MemberId: '12356789123',
      TestCode: '10545-5',
      TestName: 'Body Temperature',
      Date: '12/31/2019',
      Result: '98 F',
      RangeLowValue: '80',
      RangeLowUnit: 'F',
      RangeHighValue: '110',
      RangeHighUnit: 'F',
      RangeText: '80',
      Interpretation: 'normal',
    },
    {
      MemberId: '12356789123',
      TestCode: '10545-5',
      TestName: 'Body Temperature',
      Date: '12/31/2019',
      Result: '98 F',
      RangeLowValue: '80',
      RangeLowUnit: 'F',
      RangeHighValue: '110',
      RangeHighUnit: 'F',
      RangeText: '80',
      Interpretation: 'normal',
    },
  ],
  DrugList: [
    {
      Medications: 'DELAWARE PRESCRIPTION ASSISTANCE PROGRAM',
      MedicationName: 'Preferred Generic: Commonly prescribed generic drugs.',
      Synonym: 'METHADONE HCL',
      Ingredient: '',
      Category: '',
      Classification: '',
      DoseForum: '',
      CostType: '',
      Price: '',
      MonitoringProgram: '',
      Cost: '',
      Tier: '',
    },
  ],
};

export default Data;
